# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KETFUi1Eepedza3EVzOn_8CZ6Ol66Y8m
"""

import numpy as np
import pandas as pd

data=pd.read_csv('spam.csv')
data

data.columns

data.info()

data.isna().sum()

data['Spam']=data['Category'].apply(lambda x:1 if x=='spam' else 0)
data.head(5)

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(data.Message,data.Spam,test_size=0.25)

from sklearn.feature_extraction.text import CountVectorizer

from sklearn.naive_bayes import MultinomialNB

from sklearn.pipeline import Pipeline
clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

clf.fit(X_train,y_train)

emails=[
    'Sounds great! Are you home now?',
    'Will u meet ur dream partner soon? Is ur career off 2 a flyng start? 2 find out free, txt HORO followed by ur star sign, e. g. HORO ARIES'
]

clf.predict(emails)

clf.score(X_test,y_test)

# prompt: crate the ascending order graph in spam email

import matplotlib.pyplot as plt

# Get the number of spam emails in each category
spam_counts = data.groupby('Category')['Spam'].sum().sort_values(ascending=True)

# Create a bar chart of the spam counts
plt.bar(spam_counts.index, spam_counts.values)
plt.xlabel('Category')
plt.ylabel('Number of spam emails')
plt.title('Spam emails by category')
plt.show()

# prompt: crate how tokens have in this model

vectorizer = clf.named_steps['vectorizer']

# Get the vocabulary of the vectorizer
vocabulary = vectorizer.get_feature_names_out()

# Get the number of tokens in the vocabulary
num_tokens = len(vocabulary)

print(f"Number of tokens in the model: {num_tokens}")